### ISSUE TITLE
Pass tags to the aws_sns_topic resource.

### ISSUE THREAD

**Issue by razorsedge** [cloudposse/terraform-aws-sns-topic#6]
## Describe the Feature

Send tags to resource `aws_sns_topic`.

## Expected Behavior

Tags should be passed to the SNS topic and show in the AWS console.

## Use Case

Because, TAGs.

**Comment by jwstric2** [comment]
@razorsedge I happen to see this open issue while looking for an issue to another problem I had.  It appears that tags are supported now with this PR (https://github.com/cloudposse/terraform-aws-sns-topic/pull/26/files#diff-dc46acf24afd63ef8c556b77c126ccc6e578bc87e3aa09a931f33d9bf2532fbbR8) and went out with version 0.13.0 .. https://github.com/cloudposse/terraform-aws-sns-topic/releases/tag/0.13.0.  I'm not a project owner but might help out the cloudposse crew to tidy this one issue as closed/fixed if this is the expected behavior you were looking for.

**Comment by razorsedge** [comment]
Nice, thanks!
